# Generated by Django 4.1.7 on 2023-03-25 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_update_room_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='kosalghba',
            field=models.TextField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]