# Generated by Django 4.1.7 on 2023-03-26 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topic_room_host_alter_room_name_message_room_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='kosalghba',
        ),
    ]
