# Generated by Django 4.1.7 on 2023-04-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_room_kosalghba'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
